### ISSUE TITLE
error: no known conversion from 'X' to 'X &&' for 1st argument

### ISSUE THREAD

**Issue by pitti98** [viboes/tags#7] opened 2017-04-24 19:38 UTC
The call operator for the free function forwarders don't do perfect forwarding. The problem is that the call operator is not a template, so the expanded arguments "X &&... x" are not actually forwarding references but rvalue references which cannot bind to everything.

**Comment by viboes** [comment] 2017-04-24 20:56
I suspect that you are talking of the overload function.
Please, could you provide an example.

BTW, I'm not mainlining this repository any more. I've moved some things to the std_make repository.
If you want you can try there.

**Comment by pitti98** [comment] 2017-04-24 21:25
Yes, sorry, it's about the overload function.

I watched CppCon 2016: David Sankel “Variants: Past, Present, and Future" where he mentioned it ([https://youtu.be/k3O4EKX4z1c?t=37m41s]()). I found it fascinating and played around with it, tried to understand and re-implement it. Then I stumbled upon the problem with free functions:


```
#include <stdio.h>
#include <boost/variant.hpp>
#include "overload.hpp"

struct X {};
static void freefnx(X) { printf("X\n"); }

int main()
{
	auto ol = yafpl::overload(
			[](int i) { printf("int: %d\n", i); },
			[](const char* s) { printf("cc*: %s\n", s); },
			[](double d) { printf("double: %f\n", d); },
			&freefnx
		);

	boost::variant<int, const char*, double, X> v;
	v = 12345;
	boost::apply_visitor(ol, v);
	v = "Hello variant!";
	boost::apply_visitor(ol, v);
	v = 3.141;
	boost::apply_visitor(ol, v);
	v = X();
	boost::apply_visitor(ol, v);
	return 0;
}

```
This is with clang++ 3.9.1 and boost 1.63.

I guess it's not a huge deal, as the whole purpose is to write ad-hoc overloads with lambdas. You would not use free functions there.

**Comment by viboes** [comment] 2017-04-24 22:45
I believe this should work on the version I have in https://github.com/viboes/std-make/blob/master/include/experimental/fundamental/v3/functional/overload.hpp

BTW, with which C++ version are you compiling?

**Comment by pitti98** [comment] 2017-04-25 00:19
Yes, Isee. You changed "X&&..." to just "Args...". I guess perfect forwarding is impossible there.

I have clang set to -std=c++1z, which is the preliminary C++17 support. We're not bleeding egde at work, so I'm trying to stay up to date at home. I'm just playing around with the the cool new stuff that C++ has to offer. 

There's another thing I couldn't solve, and it seems you couldn't either: You can't have more than one final functor. Having multiple call operators in the overload set that take a variadic list of anything and try to perfect forward it is just ambiguous.

**Comment by viboes** [comment] 2017-04-25 07:17
Yes, I don't know how to perfect forward in this case.

2 final function objects seams to work as well in the std_make repo.

**Comment by pitti98** [comment] 2017-04-25 08:11
```
struct Foo final
{
	void operator()(int i) const { printf("int: %d\n", i); }
};
struct Bar final
{
	void operator()(double d) const { printf("double: %f\n", d); }
};

int main()
{
	auto ol = std::experimental::overload(
				Foo(),
				Bar()
			);

	ol(1234);

	return 0;
}

```

```
..\test3.cpp:65:2: error: call to object of type 'std::experimental::fundamental_v3::detail::overloader<Foo, Bar>' is ambiguous
        ol(1234);
        ^~
../overload.hpp:55:26: note: candidate function [with Xs = <int>]
          constexpr auto operator () (Xs &&... xs) &
                         ^
../overload.hpp:55:26: note: candidate function [with Xs = <int>]
../overload.hpp:41:26: note: candidate function [with Xs = <int>]
          constexpr auto operator () (Xs &&... xs) const &
                         ^
../overload.hpp:41:26: note: candidate function [with Xs = <int>]
```

**Comment by viboes** [comment] 2017-04-25 22:44
You are right. The problem is due to overloading of int an double. The final wrapper defines templates and so there is no better match.

I don't know if we can fix this. I'll check with other people that know better C++, but I suspect that here are the limits of perfect forwarding :( 

Thanks for catching this case. I don't know if this is a showstopper for the adoption of the overload function, but in any case, the limitation must be documented.

**Comment by pitti98** [comment] 2017-04-25 23:04
At first I thought this is a general problem, as the template parameter types get deduced from the arguments you pass, and not from the function it tries to forward them to. So accept-all overloads would all deduce to the same parameter types and automatically be ambiguous if there's more than one.

But it turns out this is not the problem. This only fails if you overload on types that are implicitly convertible to each other. In the example above, int is implicitly convertible to double, but it also fails if you have cast operators or constructors that can construct from other types you are trying to overload on:

```
struct X;
struct Y {
//	Y(const X&){} // enable this to fail
};
struct X {
//	operator Y() const { return Y(); }  // or enable this to fail
};

struct Foo final { void operator()(X) const { printf("X\n"); } };
struct Bar final { void operator()(Y) const { printf("Y\n"); } };
int main()
{
	auto ol = std::experimental::overload(Foo(), Bar());
	ol(X());
	return 0;
}

```

**Comment by viboes** [comment] 2017-04-26 16:31
Well, this is the same case. The types are implicitly convertible either because builtin conversion, constructors or conversion operators.

**Comment by viboes** [comment] 2017-04-27 05:35
I have checked with Tomasz and he has no solution in C++17. 

Some hints from Tomasz are:
* Require operator. - this will allow us to bring exact signature as delivering do.
* Fundamental Ts V2 invocation_type: but they are not implemented anywhere, and have would cause ambiguity in case of templated operator() and partial ordering
* Cast against final :( Some kind of compiler feature that would allow to unfinal and derive from final object. 

I'll close this issue. Please, could you open a new one concerning this specific issue in std_make repository?

**Closed as completed by viboes** 2017-04-27 05:35 UTC
Labels: bug, help needed
